name: cancer-detection
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - scikit-learn
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - jupyter
      - ipykernel
      - pyyaml